from __future__ import annotations

import logging
import re

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

import database.client as db
from shared.schemas import Blueprint, Project

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/export", tags=["export"])


@router.get("/{project_id}/markdown")
async def export_markdown(project_id: str):
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")
    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")
    slug = project.idea[:40].lower().replace(" ", "-").replace("/", "-")
    return Response(
        content=project.blueprint.markdown,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="foundrybuild-{slug}.md"'},
    )


@router.get("/{project_id}/readme")
async def export_readme(project_id: str):
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")
    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")
    readme = f"# {project.idea}\n\n> Generated by [FoundryBuild AI](https://foundrybuild.xyz) — Your AI CTO\n\n"
    readme += project.blueprint.markdown
    return Response(
        content=readme,
        media_type="text/markdown",
        headers={"Content-Disposition": 'attachment; filename="README.md"'},
    )


# ---------------------------------------------------------------------------
# Unicode normalisation
# ---------------------------------------------------------------------------

_UNICODE_MAP = {
    "→": "->", "←": "<-", "↑": "^", "↓": "v", "↔": "<->",
    "⟶": "->", "⟵": "<-", "⇒": "=>", "⇐": "<=",
    "•": "-", "·": "-", "‣": "-", "▸": ">",
    "—": "--", "–": "-", "…": "...",
    "“": '"', "”": '"', "‘": "'", "’": "'",
    "≥": ">=", "≤": "<=", "≈": "~", "≠": "!=",
    "×": "x", "÷": "/", "°": "deg",
    "™": "(TM)", "®": "(R)", "©": "(C)",
    "€": "EUR", "£": "GBP", "¥": "JPY",
    "✓": "OK", "✔": "OK", "✗": "X", "✘": "X",
    "★": "*", "☆": "*", "●": "-", "○": "-",
    "∞": "inf", "α": "alpha", "β": "beta", "λ": "lambda",
    "μ": "mu", "π": "pi", "σ": "sigma",
    "\u200b": "", " ": " ", " ": " ", " ": " ",
}


def _latin1_safe(text: str) -> str:
    for ch, rep in _UNICODE_MAP.items():
        text = text.replace(ch, rep)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _strip_inline(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"__(.+?)__", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", text)
    return text


# ---------------------------------------------------------------------------
# PDF class
# ---------------------------------------------------------------------------

_L_MARGIN = 15
_R_MARGIN = 15
_T_MARGIN = 24  # leaves room for header (drawn at y=8)
_B_MARGIN = 18  # leaves room for footer

_DARK = (15, 17, 22)
_ACCENT = (30, 70, 160)
_GRAY = (130, 130, 140)


class _PDF:
    """Thin wrapper that lazily imports fpdf2 and provides header/footer via subclass."""

    @staticmethod
    def make(project_idea: str, created_at: str) -> FPDF:
        from fpdf import FPDF

        idea_short = _latin1_safe(project_idea[:55])
        date_short = created_at[:10] if created_at else ""

        class BlueprintPDF(FPDF):
            def header(self_inner):
                if self_inner.page_no() <= 1:
                    return
                self_inner.set_y(8)
                self_inner.set_font("Helvetica", "", 7.5)
                self_inner.set_text_color(*_GRAY)
                self_inner.cell(self_inner.epw / 2, 5, "FoundryBuild AI  --  Engineering Blueprint", align="L")
                self_inner.cell(self_inner.epw / 2, 5, idea_short, align="R", new_x="LMARGIN", new_y="NEXT")
                y = self_inner.get_y()
                self_inner.set_draw_color(200, 202, 208)
                self_inner.line(_L_MARGIN, y, self_inner.w - _R_MARGIN, y)
                self_inner.set_draw_color(0, 0, 0)
                self_inner.set_text_color(0, 0, 0)
                self_inner.set_y(_T_MARGIN)

            def footer(self_inner):
                if self_inner.page_no() <= 1:
                    return
                self_inner.set_y(-_B_MARGIN)
                self_inner.set_draw_color(200, 202, 208)
                self_inner.line(_L_MARGIN, self_inner.get_y(), self_inner.w - _R_MARGIN, self_inner.get_y())
                self_inner.ln(1.5)
                self_inner.set_font("Helvetica", "", 7.5)
                self_inner.set_text_color(*_GRAY)
                pg = self_inner.page_no() - 1  # page 1 = cover, so content starts at 1
                self_inner.cell(self_inner.epw / 3, 5, f"Page {pg}", align="L")
                self_inner.cell(self_inner.epw / 3, 5, "foundrybuild.xyz", align="C")
                self_inner.cell(self_inner.epw / 3, 5, f"Generated {date_short}", align="R")
                self_inner.set_text_color(0, 0, 0)
                self_inner.set_draw_color(0, 0, 0)

        pdf = BlueprintPDF()
        pdf.set_margins(_L_MARGIN, _T_MARGIN, _R_MARGIN)
        pdf.set_auto_page_break(True, margin=_B_MARGIN)
        return pdf


# ---------------------------------------------------------------------------
# Cover page
# ---------------------------------------------------------------------------

def _draw_cover(pdf, idea: str, created_at: str) -> None:
    pdf.add_page()

    # Dark header band
    pdf.set_fill_color(*_DARK)
    pdf.rect(0, 0, pdf.w, 52, "F")

    # FoundryBuild wordmark in the band
    pdf.set_y(14)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(200, 205, 215)
    pdf.cell(0, 7, "FoundryBuild AI", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 110, 130)
    pdf.cell(0, 5, "foundrybuild.xyz", align="C", new_x="LMARGIN", new_y="NEXT")

    # Main title area (white background, subtle border)
    pdf.set_fill_color(255, 255, 255)
    pdf.set_draw_color(220, 222, 228)
    pdf.rect(_L_MARGIN, 65, pdf.w - _L_MARGIN - _R_MARGIN, 85, "FD")

    pdf.set_y(75)
    pdf.set_x(_L_MARGIN)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_DARK)
    safe_idea = _latin1_safe(idea[:100])
    pdf.multi_cell(pdf.w - _L_MARGIN - _R_MARGIN - 10, 12, safe_idea, align="C")

    pdf.ln(6)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_GRAY)
    pdf.cell(0, 7, "Engineering Blueprint", align="C", new_x="LMARGIN", new_y="NEXT")

    # Metadata row
    pdf.set_y(160)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_GRAY)
    date_str = created_at[:10] if created_at else "-"
    pdf.cell(0, 6, f"Generated  {date_str}", align="C", new_x="LMARGIN", new_y="NEXT")

    # Bottom accent strip
    pdf.set_fill_color(*_ACCENT)
    pdf.rect(0, pdf.h - 8, pdf.w, 8, "F")

    pdf.set_text_color(0, 0, 0)
    pdf.set_draw_color(0, 0, 0)


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def _ensure_space(pdf, min_mm: float = 35.0) -> None:
    """Add a new page if less than min_mm remains before the bottom margin."""
    if pdf.get_y() > pdf.h - pdf.b_margin - min_mm:
        pdf.add_page()


def _render_table_rows(pdf, rows: list) -> None:
    if not rows:
        return
    num_cols = max(len(r) for r in rows)
    if not num_cols:
        return

    page_w = pdf.w - pdf.l_margin - pdf.r_margin

    # Proportional column widths based on max content length per column
    col_maxlen = [1] * num_cols
    for row in rows:
        for c in range(min(len(row), num_cols)):
            col_maxlen[c] = max(col_maxlen[c], len(row[c].strip()) or 1)
    total_len = sum(col_maxlen) or 1
    raw_widths = [(l / total_len) * page_w for l in col_maxlen]
    # Clamp each column to at least 10mm, then normalize to exactly page_w
    MIN_COL = 10.0
    col_widths = [max(w, MIN_COL) for w in raw_widths]
    total_w = sum(col_widths)
    col_widths = [w * page_w / total_w for w in col_widths]

    cell_h = 6.5

    for idx, row in enumerate(rows):
        is_header = idx == 0

        # Check page break before each row
        if pdf.get_y() + cell_h > pdf.h - pdf.b_margin:
            pdf.add_page()
            # Re-render header row after page break
            if not is_header:
                _render_header_row(pdf, rows[0], col_widths, cell_h)

        if is_header:
            _render_header_row(pdf, row, col_widths, cell_h)
        else:
            pdf.set_font("Helvetica", "", 8.5)
            fill_color = (248, 249, 251) if idx % 2 == 0 else (255, 255, 255)
            pdf.set_fill_color(*fill_color)
            pdf.set_text_color(30, 30, 40)
            for c in range(num_cols):
                raw = row[c].strip() if c < len(row) else ""
                cell_text = _latin1_safe(_strip_inline(raw))
                max_chars = max(int(col_widths[c] / 1.65), 10)
                if len(cell_text) > max_chars:
                    cell_text = cell_text[:max_chars - 2] + ".."
                pdf.cell(col_widths[c], cell_h, cell_text, border=1, fill=True, new_x="RIGHT", new_y="TOP")
            pdf.ln(cell_h)

    pdf.set_font("Helvetica", size=11)
    pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)


def _render_header_row(pdf, row: list, col_widths: list, cell_h: float) -> None:
    num_cols = len(col_widths)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_fill_color(*_DARK)
    pdf.set_text_color(220, 222, 230)
    for c in range(num_cols):
        raw = row[c].strip() if c < len(row) else ""
        cell_text = _latin1_safe(_strip_inline(raw))
        max_chars = max(int(col_widths[c] / 1.65), 10)
        if len(cell_text) > max_chars:
            cell_text = cell_text[:max_chars - 2] + ".."
        pdf.cell(col_widths[c], cell_h, cell_text, border=1, fill=True, new_x="RIGHT", new_y="TOP")
    pdf.ln(cell_h)


def _render_markdown_pdf(pdf, markdown_text: str) -> None:
    """Render markdown line-by-line to fpdf2, bypassing write_html()."""
    lines = markdown_text.splitlines()
    i = 0
    consecutive_blanks = 0

    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # --- Blank line ---
        if not stripped:
            consecutive_blanks += 1
            if consecutive_blanks == 1:
                pdf.ln(2)
            i += 1
            continue
        consecutive_blanks = 0

        # --- Fenced code block ---
        if stripped.startswith("```"):
            i += 1
            code_lines = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            if code_lines:
                _ensure_space(pdf, 20)
                pdf.set_font("Courier", "", 8)
                pdf.set_fill_color(240, 241, 244)
                pdf.set_text_color(30, 30, 40)
                for cl in code_lines:
                    safe = _latin1_safe(cl) or " "
                    if len(safe) > 100:
                        safe = safe[:97] + "..."
                    pdf.set_x(pdf.l_margin)
                    pdf.multi_cell(0, 4.5, safe, fill=True)
                pdf.set_font("Helvetica", size=11)
                pdf.set_fill_color(255, 255, 255)
                pdf.set_text_color(0, 0, 0)
                pdf.ln(2)
            i += 1  # closing ```
            continue

        # --- Markdown table ---
        if stripped.startswith("|"):
            table_rows: list[list[str]] = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                row = lines[i].strip()
                if not re.fullmatch(r"\|[-| :]+\|", row):
                    cells = [c.strip() for c in row.strip("|").split("|")]
                    table_rows.append(cells)
                i += 1
            if table_rows:
                _ensure_space(pdf, 25)
                pdf.ln(2)
                _render_table_rows(pdf, table_rows)
            continue

        # --- H1 ---
        if re.match(r"^# [^#]", stripped):
            _ensure_space(pdf, 50)
            heading = _latin1_safe(_strip_inline(stripped[2:]))
            # Decorative full-width bar
            pdf.set_fill_color(*_DARK)
            pdf.rect(pdf.l_margin - 2, pdf.get_y(), pdf.w - pdf.l_margin - pdf.r_margin + 4, 11, "F")
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(230, 232, 238)
            pdf.cell(0, 11, f"  {heading}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", size=11)
            pdf.ln(3)

        # --- H2 ---
        elif re.match(r"^## [^#]", stripped):
            _ensure_space(pdf, 38)
            heading = _latin1_safe(_strip_inline(stripped[3:]))
            pdf.ln(1)
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(*_ACCENT)
            pdf.multi_cell(0, 7, heading)
            # Thin underline
            y = pdf.get_y()
            pdf.set_draw_color(*_ACCENT)
            pdf.set_line_width(0.4)
            pdf.line(pdf.l_margin, y, pdf.l_margin + 50, y)
            pdf.set_line_width(0.2)
            pdf.set_draw_color(0, 0, 0)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", size=11)
            pdf.ln(2)

        # --- H3 ---
        elif re.match(r"^### [^#]", stripped):
            _ensure_space(pdf, 28)
            heading = _latin1_safe(_strip_inline(stripped[4:]))
            pdf.ln(1)
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(40, 50, 70)
            pdf.multi_cell(0, 6.5, heading)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", size=11)
            pdf.ln(1)

        # --- H4+ ---
        elif re.match(r"^#{4,} ", stripped):
            _ensure_space(pdf, 22)
            m = re.match(r"^(#{4,}) ", stripped)
            rest = _latin1_safe(_strip_inline(stripped[len(m.group(1)) + 1:]))
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "BI", 10)
            pdf.set_text_color(60, 70, 90)
            pdf.multi_cell(0, 6, rest)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", size=11)

        # --- Bullet list item ---
        elif re.match(r"^[-*•●] ", stripped):
            text = _latin1_safe(_strip_inline(stripped[2:]))
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(30, 30, 40)
            # Indent and bullet
            pdf.set_x(pdf.l_margin + 4)
            pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 4, 5.5, f"-  {text}")
            pdf.set_text_color(0, 0, 0)

        # --- Numbered list item ---
        elif re.match(r"^\d+\. ", stripped):
            m = re.match(r"^(\d+)\. ", stripped)
            text = _latin1_safe(_strip_inline(stripped[len(m.group(0)):]))
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(30, 30, 40)
            pdf.set_x(pdf.l_margin + 4)
            pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 4, 5.5, f"{m.group(1)}.  {text}")
            pdf.set_text_color(0, 0, 0)

        # --- Horizontal rule ---
        elif re.match(r"^[-_*]{3,}$", stripped):
            pdf.ln(2)
            y = pdf.get_y()
            pdf.set_draw_color(200, 202, 208)
            pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
            pdf.set_draw_color(0, 0, 0)
            pdf.ln(3)

        # --- Regular paragraph ---
        else:
            text = _latin1_safe(_strip_inline(stripped))
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "", 10.5)
            pdf.set_text_color(30, 30, 40)
            pdf.multi_cell(0, 5.5, text)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

        i += 1


# ---------------------------------------------------------------------------
# Structured blueprint renderer — renders every field directly from Blueprint
# ---------------------------------------------------------------------------

def _h1(pdf, text: str) -> None:
    _ensure_space(pdf, 50)
    heading = _latin1_safe(text)
    pdf.set_fill_color(*_DARK)
    pdf.rect(pdf.l_margin - 2, pdf.get_y(), pdf.w - pdf.l_margin - pdf.r_margin + 4, 11, "F")
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(230, 232, 238)
    pdf.cell(0, 11, f"  {heading}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=11)
    pdf.ln(3)


def _h2(pdf, text: str) -> None:
    _ensure_space(pdf, 38)
    pdf.ln(1)
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_ACCENT)
    pdf.multi_cell(0, 7, _latin1_safe(text))
    y = pdf.get_y()
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.4)
    pdf.line(pdf.l_margin, y, pdf.l_margin + 50, y)
    pdf.set_line_width(0.2)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=11)
    pdf.ln(2)


def _para(pdf, text: str) -> None:
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "", 10.5)
    pdf.set_text_color(30, 30, 40)
    pdf.multi_cell(0, 5.5, _latin1_safe(_strip_inline(text)))
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


def _bullet_list(pdf, items: list[str]) -> None:
    pdf.set_font("Helvetica", "", 10.5)
    pdf.set_text_color(30, 30, 40)
    for item in items:
        if not item:
            continue
        pdf.set_x(pdf.l_margin + 4)
        pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 4, 5.5, f"-  {_latin1_safe(_strip_inline(item))}")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


def _kv(pdf, label: str, value: str) -> None:
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_DARK)
    pdf.cell(45, 5.5, _latin1_safe(label) + ":", new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 40)
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 45, 5.5, _latin1_safe(_strip_inline(value)))
    pdf.set_text_color(0, 0, 0)


def _render_blueprint_structured(pdf, bp: Blueprint) -> None:
    # ---- Executive Summary ----
    _h1(pdf, "Executive Summary")
    _para(pdf, bp.executive_summary)

    # ---- Problem Statement ----
    _h1(pdf, "Problem Statement")
    _para(pdf, bp.problem_statement)

    # ---- Objectives ----
    if bp.objectives:
        _h1(pdf, "Objectives")
        _bullet_list(pdf, bp.objectives)

    # ---- Assumptions & Constraints ----
    if bp.assumptions or bp.constraints:
        _h1(pdf, "Assumptions & Constraints")
        if bp.assumptions:
            _h2(pdf, "Assumptions")
            _bullet_list(pdf, bp.assumptions)
        if bp.constraints:
            _h2(pdf, "Constraints")
            _bullet_list(pdf, bp.constraints)

    # ---- System Architecture ----
    _h1(pdf, "System Architecture")
    _para(pdf, bp.system_architecture)

    # ---- Technology Stack ----
    _h1(pdf, "Technology Stack")
    if bp.tech_stack:
        _h2(pdf, "Core Stack")
        _bullet_list(pdf, bp.tech_stack)
    if bp.hardware:
        _h2(pdf, "Hardware Components")
        _bullet_list(pdf, bp.hardware)
    if bp.software_components:
        _h2(pdf, "Software Components")
        _bullet_list(pdf, bp.software_components)
    if bp.apis:
        _h2(pdf, "APIs & Services")
        _bullet_list(pdf, bp.apis)
    if bp.libraries:
        _h2(pdf, "Libraries & Frameworks")
        _bullet_list(pdf, bp.libraries)
    if bp.models:
        _h2(pdf, "AI Models")
        _bullet_list(pdf, bp.models)
    if bp.datasets:
        _h2(pdf, "Datasets")
        _bullet_list(pdf, bp.datasets)

    # ---- Development Roadmap ----
    if bp.roadmap:
        _h1(pdf, "Development Roadmap")
        for m in bp.roadmap:
            _ensure_space(pdf, 40)
            _h2(pdf, f"Phase {m.phase}: {m.title} ({m.duration_weeks} weeks)")
            if m.objectives:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Objectives", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, m.objectives)
            if m.deliverables:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Deliverables", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, m.deliverables)
            if m.success_criteria:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Success Criteria", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, m.success_criteria)
            if m.dependencies:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Dependencies", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, m.dependencies)
            pdf.set_text_color(0, 0, 0)

    # ---- Bill of Materials ----
    if bp.bom:
        _h1(pdf, "Bill of Materials & Cost Estimates")
        _ensure_space(pdf, 25)
        header = ["Component", "Qty", "Unit Cost (USD)", "Total (USD)", "Notes"]
        rows = [header]
        for b in bp.bom:
            alts = ", ".join(b.alternatives) if b.alternatives else ""
            note = _latin1_safe(f"{b.notes} {('Alt: ' + alts) if alts else ''}".strip())
            rows.append([
                _latin1_safe(b.component),
                str(b.quantity),
                f"${b.unit_cost_usd:,.2f}",
                f"${b.total_cost_usd:,.2f}",
                note[:60],
            ])
        _render_table_rows(pdf, rows)

        # Cost summary
        _h2(pdf, "Variant Cost Summary")
        rows2 = [["Variant", "Total (USD)"]]
        for variant, cost in bp.estimated_cost.items():
            rows2.append([variant.capitalize(), f"${cost:,.2f}"])
        _render_table_rows(pdf, rows2)

    # ---- Skill Requirements ----
    if bp.skill_requirements:
        _h1(pdf, "Skill Requirements & Gap Analysis")
        rows = [["Skill", "Level Required", "Have It?", "Learn (weeks)", "Resources"]]
        for s in bp.skill_requirements:
            resources = ", ".join(s.resources[:2]) if s.resources else ""
            rows.append([
                _latin1_safe(s.skill),
                s.level_required,
                "Yes" if s.currently_have else "No",
                str(s.learning_time_weeks),
                _latin1_safe(resources)[:50],
            ])
        _render_table_rows(pdf, rows)

    # ---- Risk Analysis ----
    if bp.risks:
        _h1(pdf, "Risk Analysis")
        rows = [["Category", "Description", "Likelihood", "Impact", "Mitigation"]]
        for r in bp.risks:
            rows.append([
                _latin1_safe(r.category),
                _latin1_safe(_strip_inline(r.description))[:80],
                r.likelihood,
                r.impact,
                _latin1_safe(_strip_inline(r.mitigation))[:80],
            ])
        _render_table_rows(pdf, rows)

    # ---- Design Variants ----
    if bp.three_designs:
        _h1(pdf, "Three Design Alternatives")
        for d in bp.three_designs:
            _ensure_space(pdf, 45)
            _h2(pdf, f"{d.label} — Est. ${d.estimated_cost_usd:,.0f}")
            _kv(pdf, "Complexity", d.complexity)
            _kv(pdf, "Performance", _strip_inline(d.performance))
            if d.tech_stack:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Tech Stack", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, d.tech_stack)
            if d.advantages:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Advantages", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, d.advantages)
            if d.disadvantages:
                pdf.set_font("Helvetica", "B", 9.5)
                pdf.set_text_color(*_DARK)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Disadvantages", new_x="LMARGIN", new_y="NEXT")
                _bullet_list(pdf, d.disadvantages)
            pdf.set_text_color(0, 0, 0)

    # ---- Devil's Advocate ----
    dc = bp.devil_critique
    if dc:
        _h1(pdf, "Devil's Advocate Critique")
        sections_dc = [
            ("Wrong Assumptions", dc.wrong_assumptions),
            ("Failure Points", dc.failure_points),
            ("Over-Engineered", dc.over_engineered),
            ("Under-Engineered", dc.under_engineered),
            ("Hidden Costs", dc.hidden_costs),
            ("Simplifications", dc.simplifications),
            ("Senior Engineer Challenges", dc.senior_challenges),
        ]
        for title, items in sections_dc:
            if items:
                _h2(pdf, title)
                _bullet_list(pdf, items)

    # ---- Feasibility ----
    f = bp.feasibility
    if f:
        _h1(pdf, "Feasibility Assessment")
        rows = [["Dimension", "Score", "Explanation"]]
        dims = [
            ("Technical Feasibility", f.technical_feasibility, f.explanations.technical_feasibility if f.explanations else ""),
            ("Commercial Potential", f.commercial_potential, f.explanations.commercial_potential if f.explanations else ""),
            ("Innovation", f.innovation, f.explanations.innovation if f.explanations else ""),
            ("Complexity", f.complexity, f.explanations.complexity if f.explanations else ""),
            ("Scalability", f.scalability, f.explanations.scalability if f.explanations else ""),
            ("Maintainability", f.maintainability, f.explanations.maintainability if f.explanations else ""),
        ]
        for name, score, expl in dims:
            rows.append([name, f"{score}/100", _latin1_safe(_strip_inline(expl))[:100]])
        _render_table_rows(pdf, rows)
        _h2(pdf, "Overall Recommendation")
        _para(pdf, f.overall_recommendation)

    # ---- GitHub Resources ----
    if bp.github_repos:
        _h1(pdf, "GitHub Resources")
        rows = [["Repository", "Stars", "Language", "Relevance"]]
        for r in bp.github_repos:
            rows.append([
                _latin1_safe(r.name),
                f"{r.stars:,}" if r.stars else "-",
                _latin1_safe(r.language or "-"),
                _latin1_safe(_strip_inline(r.relevance))[:80],
            ])
        _render_table_rows(pdf, rows)

    # ---- Research References ----
    if bp.research_papers:
        _h1(pdf, "Research References")
        for p in bp.research_papers:
            _ensure_space(pdf, 20)
            authors = ", ".join(p.authors[:3]) + (" et al." if len(p.authors) > 3 else "")
            year = f" ({p.year})" if p.year else ""
            _kv(pdf, "Title", p.title)
            if authors:
                _kv(pdf, "Authors", authors + year)
            if p.url:
                _kv(pdf, "URL", p.url[:80])
            if p.abstract:
                _kv(pdf, "Abstract", _strip_inline(p.abstract)[:200])
            if p.relevance:
                _kv(pdf, "Relevance", _strip_inline(p.relevance))
            pdf.ln(3)

    # ---- Future Work ----
    if bp.future_work:
        _h1(pdf, "Future Work")
        _bullet_list(pdf, bp.future_work)

    # ---- Team & People ----
    if bp.talent:
        t = bp.talent
        _h1(pdf, "Team & People")
        if t.key_roles_needed:
            _h2(pdf, "Key Roles Needed")
            _bullet_list(pdf, t.key_roles_needed)
        if t.notable_people:
            _h2(pdf, "Notable Experts")
            rows = [["Name", "Platform", "Role", "Relevance"]]
            for p in t.notable_people:
                rows.append([
                    _latin1_safe(p.name or "-"),
                    _latin1_safe(p.platform or "-"),
                    _latin1_safe(p.role or "-"),
                    _latin1_safe(_strip_inline(p.relevance or "-"))[:60],
                ])
            _render_table_rows(pdf, rows)
        if t.communities:
            _h2(pdf, "Communities")
            rows = [["Community", "Platform", "Description"]]
            for c in t.communities:
                rows.append([
                    _latin1_safe(c.name or "-"),
                    _latin1_safe(c.platform or "-"),
                    _latin1_safe(_strip_inline(c.description or "-"))[:80],
                ])
            _render_table_rows(pdf, rows)
        if t.hiring_platforms:
            _h2(pdf, "Where to Hire")
            _bullet_list(pdf, t.hiring_platforms)
        if t.outreach_tips:
            _h2(pdf, "Outreach Tips")
            _para(pdf, t.outreach_tips)


# ---------------------------------------------------------------------------
# PDF export endpoint
# ---------------------------------------------------------------------------

@router.get("/{project_id}/pdf")
async def export_pdf(project_id: str):
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    bp = project.blueprint

    try:
        pdf = _PDF.make(project.idea, bp.created_at)

        # Cover page
        _draw_cover(pdf, project.idea, bp.created_at)

        # Content pages — render from structured fields for completeness
        pdf.add_page()
        _render_blueprint_structured(pdf, bp)

        pdf_bytes = pdf.output()
        slug = project.idea[:40].lower().replace(" ", "-")
        filename = f"foundrybuild-{slug}.pdf"

        return Response(
            content=bytes(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as exc:
        logger.exception("PDF generation failed for project %s", project_id)
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")
