from __future__ import annotations
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from shared.schemas import Project
import database.client as db

router = APIRouter(prefix="/export", tags=["export"])


@router.get("/{project_id}/markdown")
async def export_markdown(project_id: str):
    """Export blueprint as Markdown."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    slug = project.idea[:40].lower().replace(" ", "-").replace("/", "-")
    filename = f"foundrybuild-{slug}.md"

    return Response(
        content=project.blueprint.markdown,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{project_id}/readme")
async def export_readme(project_id: str):
    """Export blueprint as a GitHub README.md."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    # Prepend a GitHub-flavored README header
    readme = f"# {project.idea}\n\n> Generated by [FoundryBuild AI](https://foundrybuild.xyz) — Your AI CTO\n\n"
    readme += project.blueprint.markdown

    return Response(
        content=readme,
        media_type="text/markdown",
        headers={"Content-Disposition": 'attachment; filename="README.md"'},
    )


@router.get("/{project_id}/pdf")
async def export_pdf(project_id: str):
    """Export blueprint as PDF."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    try:
        from fpdf import FPDF
        import markdown2

        html = markdown2.markdown(
            project.blueprint.markdown,
            extras=["tables", "fenced-code-blocks", "header-ids"],
        )

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", size=11)

        # fpdf2 write_html for rich content
        pdf.write_html(html)

        pdf_bytes = pdf.output()
        slug = project.idea[:40].lower().replace(" ", "-")
        filename = f"foundrybuild-{slug}.pdf"

        return Response(
            content=bytes(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")
