from __future__ import annotations
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from shared.schemas import Project
import database.client as db

router = APIRouter(prefix="/export", tags=["export"])


@router.get("/{project_id}/markdown")
async def export_markdown(project_id: str):
    """Export blueprint as Markdown."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    slug = project.idea[:40].lower().replace(" ", "-").replace("/", "-")
    filename = f"foundrybuild-{slug}.md"

    return Response(
        content=project.blueprint.markdown,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{project_id}/readme")
async def export_readme(project_id: str):
    """Export blueprint as a GitHub README.md."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    # Prepend a GitHub-flavored README header
    readme = f"# {project.idea}\n\n> Generated by [FoundryBuild AI](https://foundrybuild.xyz) — Your AI CTO\n\n"
    readme += project.blueprint.markdown

    return Response(
        content=readme,
        media_type="text/markdown",
        headers={"Content-Disposition": 'attachment; filename="README.md"'},
    )


_UNICODE_MAP = {
    "→": "->", "←": "<-", "↑": "^", "↓": "v", "↔": "<->",
    "⟶": "->", "⟵": "<-", "⇒": "=>", "⇐": "<=",
    "•": "-", "·": "-", "‣": "-", "▸": ">",
    "—": "--", "–": "-", "…": "...",
    "“": '"', "”": '"', "‘": "'", "’": "'",
    "≥": ">=", "≤": "<=", "≈": "~", "≠": "!=",
    "×": "x", "÷": "/", "°": "deg",
    "™": "(TM)", "®": "(R)", "©": "(C)",
    "€": "EUR", "£": "GBP", "¥": "JPY",
    "✓": "OK", "✔": "OK", "✗": "X", "✘": "X",
    "★": "*", "☆": "*", "●": "-", "○": "-",
    "∞": "inf", "α": "alpha", "β": "beta", "λ": "lambda",
    "μ": "mu", "π": "pi", "σ": "sigma",
    "​": "", " ": " ", " ": " ", " ": " ",
}


def _latin1_safe(text: str) -> str:
    for ch, rep in _UNICODE_MAP.items():
        text = text.replace(ch, rep)
    # Replace any remaining non-latin1 chars with '?'
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _sanitize_html(html: str) -> str:
    import re, html as html_mod
    # Unescape all HTML entities first so we can normalize them
    unescaped = html_mod.unescape(html)
    # Apply our char map to the unescaped text (preserving tags)
    for ch, rep in _UNICODE_MAP.items():
        unescaped = unescaped.replace(ch, rep)
    # Encode to latin-1, replacing unknown chars — tags are ASCII so they survive
    return unescaped.encode("latin-1", errors="replace").decode("latin-1")


@router.get("/{project_id}/pdf")
async def export_pdf(project_id: str):
    """Export blueprint as PDF."""
    data = await db.get_project(project_id)
    if not data:
        raise HTTPException(status_code=404, detail="Project not found")

    project = Project(**data)
    if not project.blueprint:
        raise HTTPException(status_code=400, detail="Blueprint not ready")

    try:
        from fpdf import FPDF
        import markdown2

        safe_md = _latin1_safe(project.blueprint.markdown)
        html = markdown2.markdown(
            safe_md,
            extras=["tables", "fenced-code-blocks", "header-ids"],
        )
        safe_html = _sanitize_html(html)

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", size=11)
        pdf.write_html(safe_html)

        pdf_bytes = pdf.output()
        slug = project.idea[:40].lower().replace(" ", "-")
        filename = f"foundrybuild-{slug}.pdf"

        return Response(
            content=bytes(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")
